### ISSUE TITLE
Add keystroke control to Creature Randomizer

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#13]
"r" would be ideal, so I can sit here pushing the "r" key over and over without making my arm sore or wasting precious nanoseconds for randomizer gratification.

**Comment by toolness** [comment]
Ok @ninapaley I've just added a keyboard shortcut for it which, on Macs, should be activated by pressing <kbd>Control</kbd> + <kbd>Option</kbd> + <kbd>R</kbd>.  Does that seem to work for you?  (Please give the change a few minutes to make it to the web; you'll know the keyboard shortcut is possible if you see the "R" of "Randomize!" underlined.)

**Comment by toolness** [comment]
I'm going to close this issue for now, but @ninapaley if you find that you're unable to trigger the shortcut feel free to re-open it!
