### ISSUE TITLE
Nest images

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#17]
Allow symbols to nest inside other symbols, as specified by the magenta bounding box in specs layer.
**Invert the color of the nested symbol**: switch white fill to black fill, black stroke to white stroke, if symbol is overlaid on a white fill. Symbols nested in bounding box that is NOT over a fill color do not get inverted. See image:
![nest color inversion](https://user-images.githubusercontent.com/79212762/108601274-72cd2100-7361-11eb-9ba4-a0bf290c7487.png)

Some symbols, like "eye" and the towers, have both black and white fills. If the magenta bounding box is over a black fill, the nested symbol atop it will maintain its white fill.
![nest color inversion2](https://user-images.githubusercontent.com/79212762/108601403-069eed00-7362-11eb-9364-780a75efc6aa.png)

**Comment by ninapaley** [comment]
FWIW this is the next feature I'd like to see. It will affect how I proceed designing symbols. If the color inversion is any roadblock, feel free to skip it. @toolness

**Comment by toolness** [comment]
Ok cool!  I noticed that the eye has changed though, and now looks like this:

> ![image](https://user-images.githubusercontent.com/124687/108930577-2a895980-7614-11eb-80c7-35d59a09302a.png)

That is, it doesn't seem to have a fill in the center anymore... in fact I can't seem to find any symbols that have a fill in the nesting area, is that right?

**Comment by ninapaley** [comment]
Yeah I restored empty spaces because they look better than black fills while there's nothing nested in there.
Is it ok for me to leave them as is for now, and not worry about inverting any colors? Once I can see what nesting looks like in practice, we can address fills and color inversions.

**Comment by ninapaley** [comment]
Also if we have a rule that something is ALWAYS nested in the eye, I can take out that dot in the middle. It's only there as an aesthetic placeholder. I'd originally imagined the eye as always having something nested in it instead.

**Comment by toolness** [comment]
Ohh ok that makes sense!  Thanks for the clarifications.

Ok, I've added very very basic support for nesting in #30!  See its description for more details about the limitations.  I'll be fixing those limitations in the coming days but for now I am pooooped.

**Comment by ninapaley** [comment]
This helps me a lot! Thanks @toolness . 
Clearly some symbols are suited to enclosing others, and some are suited to being enclosed. It's probably time for us to add those TOML or YAML files to specify, so we don't get a lot of un-aesthetic combinations.

**Comment by toolness** [comment]
Ok, I've just added randomly generated nesting in complexity levels 0 thru 4!  See #34 more more info... right now we'll only add nesting for symbols that **demand it at all costs** in their TOML metadata.  And we also obey the `always_be_nested` property too.

**Comment by ninapaley** [comment]
I've made TOML for everything! Many of these I will go back and change later. I told some to "always nest" just because I wanted to see what they'd look like. With additional rules (like #38 ) I can return them to the default.

I filled a lot of spaces with black, and even exported some symbols with all black fills and white strokes, so see how it looks. In addition to new issue #39 to generate inverted versions of every symbol, it's also time to invert the colors of the nested symbol. If it's on a (predominately) black fill with white strokes, it should always have a white fill with black strokes, and vice-versa.

**Comment by ninapaley** [comment]
I can specify in every TOML whether a symbol's bounding box is over a default black or white area, which determines whether the symbol nested on it is color inverted or not. The center of the "eye", for example, is black; a symbol nested on it does NOT need to be inverted. The "circle" is white, and anything nested on it does need to be inverted. Maybe a line like, "invert_nested = true" or false could be added? Again, I will do back and set all the symbols to (predominately) white fills and black strokes as defaults, even though some are temporarily inverted at the moment, so I can make fun images like these:
![Coveted Crown](https://user-images.githubusercontent.com/79212762/109434120-4b1d2f00-79d9-11eb-981a-a29c525cfd14.png)
![The Folly of Man](https://user-images.githubusercontent.com/79212762/109434128-5708f100-79d9-11eb-807d-920089617cb7.png)

**Comment by ninapaley** [comment]
I'd like a "never_be_nested" line. If I keep the black and white color scheme on "snake_helix", for example, it would have that in its TOML file. I don't need a "never_nest" line because I simply don't include a bounding box on those symbols.

I'd put additional like this in the TOMLs, but I don't want the program to explode as apparently it will if there's no code for it yet. Should I think of a bunch of potential true/false lines like these now, even if it may be a while before they do anything?

**Comment by toolness** [comment]
Oh good idea!

Hmm, it sounds like I need to relax the "crash early" philosophy so we can iterate more freely!  I've changed things up in c62214186be49b4994e380d1a0d9b9138bd1ceb2 so that now the website builder will just log a warning if it runs into a metadata property it doesn't recognize, instead of exploding.  So you can go ahead and start adding `never_nest` and anything else you want to the TOML files!

**Comment by toolness** [comment]
> I can specify in every TOML whether a symbol's bounding box is over a default black or white area, which determines whether the symbol nested on it is color inverted or not.

That would be awesome! I noticed, though that, some of the symbols have multiple nesting areas... Do you think you'll ever make a symbol where e.g. one of the nesting areas should have an inverted symbol while the other has a non-inverted one?  If not, then this should be easy, we can just have a boolean property called e.g. `always_invert_nested_symbols` or something, but otherwise we might have to think of a way to support the unusual use case (I have some ideas which I can propose if you think it's likely).

**Comment by toolness** [comment]
Oh, when you add new metadata properties, can you file separate issues for each one? e.g. once you start populating files with `never_be_nested`, can you file an issue for me to add support for the property in the code?  That will make it easy for me to keep track of which ones I still need to add support for.

**Comment by toolness** [comment]
Err, I just added support for `never_be_nested` in b1b0176e4aac356563ea58618e672397beb7d212 so don't worry about filing an issue for that... you should be able to go ahead and use it!

Note that I've added the line (and documentation) for this new property in `_template.toml` but you will have to manually add it to all the other existing `.toml` files... if a file doesn't explicitly specify a value for `never_be_nested` it will default to `false`, though, so you only need to add it to a `.toml` file if you are setting it to `true`. Does that make sense?

**Comment by ninapaley** [comment]
Yes that makes sense, and should make even more sense tomorrow when I re-read it and get to work.
Nice that I won't have to set specs for absolutely everything in every file! I can just work on the ones that need specific behaviors.

**Comment by ninapaley** [comment]
> I noticed, though that, some of the symbols have multiple nesting areas... Do you think you'll ever make a symbol where e.g. one of the nesting areas should have an inverted symbol while the other has a non-inverted one? If not, then this should be easy, we can just have a boolean property called e.g. `always_invert_nested_symbols` or something, but otherwise we might have to think of a way to support the unusual use case (I have some ideas which I can propose if you think it's likely).

It would be nice to be able to do this, but there are many other more important issues I'd rather see worked on first, so it's not a high priority for me right now.

**Comment by ninapaley** [comment]
I'm ready to add a line in the TOML files that determines whether the nested object is inverted or not. How shall I express this? Would it be:

"invert_nested = true" (or false)?

Please advise.

**Comment by toolness** [comment]
Nice, I think that works well!  You should be able to add it without the website builder exploding--maybe add the property to one `toml` file like you did with the yellow SVG, just to make sure nothing explodes?

**Comment by ninapaley** [comment]
I uploaded "circle.toml" successfully! Will go modify the rest of the relevant TOMLs now. If a TOML _doesn't_ have "invert_nested" line, that means the colors of any symbol nested on it _won't_ change, right?

**Comment by toolness** [comment]
Nice!  Yup, that is correct, `invert_nested` will default to `false` if it's not explicitly mentioned in a TOML file.

**Comment by toolness** [comment]
Ok I just added support for `invert_nested`, so anything with that set to `true` should be reflected now in the random creature generator (excluding the "bonkers" complexity level which has a totally different algorithm).

**Comment by ninapaley** [comment]
Yay it works! Thanks.
