### ISSUE TITLE
Consider using TOML or YAML files to describe metadata about symbols

### ISSUE THREAD

**Issue by toolness** [toolness/mystic-symbolic#20]
Currently we'd like to have metadata about symbols, e.g.:

* "This symbol represents something that comes in pairs", e.g. wings
* "This symbol should always have something attached to its horn attachment point"
* "This symbol should always have something in its nesting area"

It has also been brought up that it'd be nice to assign tags/categories to symbols, so that e.g. if a user wanted to generate a random morbid creature, the generator could filter out any symbols that didn't have the "morbid" tag.

One way to accomplish these goals is by having a [TOML](https://en.wikipedia.org/wiki/TOML) or [YAML](https://en.wikipedia.org/wiki/YAML) file alongside each SVG file.  For instance, the `wing_butterfly.svg` file could have a `wing_butterfly.toml` file next to it (i.e., in the same directory) with the following content:

```toml
comes_in_pairs = true
tags = ["faerie", "awesome"]
```

This would tell the program that the `wing_butterfly.svg` symbol should come in pairs, and that it has the tags "faerie" and "awesome".

@ninapaley does this make sense? Curious what your thoughts are.

**Comment by ninapaley** [comment]
I'm intrigued. How would I create these files? Where would I store them? Would there be a bunch of tags I could click every time I uploaded a new symbol, that would translate to code like this?

**Comment by toolness** [comment]
Oh, they would just be text files you create, using a tool like the built-in [TextEdit](https://en.wikipedia.org/wiki/TextEdit) that came with your Mac, or (more likely) with a tool that supports syntax highlighting like [Textastic](https://www.textasticapp.com/mac.html) or [Visual Studio Code](https://code.visualstudio.com/).

Probably the easiest workflow would be for me to make a simple "starter template" in the SVG folder, called e.g. `example_metadata.toml`, which you would make a copy of and rename to `[name of svg].toml`, so e.g. if you were making metadata for `muscle_arm.svg` you'd rename it to `muscle_arm.toml`.  It'd contain a bunch of default values, along with some documentation in the form of code comments.  Then you'd edit it using the text editor of your choice.

Unfortunately you _would_ be typing in the actual code--there wouldn't be a graphical user interface--but the syntax is relatively simple.  An alternative to the TOML syntax that is more human-friendly is YAML; the YAML equivalent of the example I mentioned above would be something like this:

```yaml
comes_in_pairs: true
tags:
  - faerie
  - awesome
```

I'm guessing you might be more comfortable with YAML, it's much less "codey", e.g. you generally don't have to worry about doing anything with square brackets or double quotes.

**Comment by toolness** [comment]
Oh, actually another alternative would be for you to simply create and edit these TOML/YAML files using the GitHub web interface!  I'd forgotten about that.  That way you wouldn't need any kind of text editor on your mac, you'd just use GitHub's website, and it would provide you with syntax highlighting too, which would be helpful.

**Comment by ninapaley** [comment]
Ah got it, a text file with the same name as the svg but ending in .toml or .yaml instead of .svg. Thanks!

**Comment by ninapaley** [comment]
@toolness How exactly do I use GitHub's web interface to create a TOML file for an svg symbol? Can you make a template?

**Comment by ninapaley** [comment]
@toolness I'd like to start working on this, since we have nesting starting. I'd like to specify things like:
"this symbol should always or often have something nested inside it" (ie circle, ring, triangle)
"this symbol should never be nested inside of something else" (ie goat_horn, unihorn)

How do we discuss terminology? Would the words be "nest" for having something inside, "nested" for being inside something else? Or enclose/enclosed?

**Comment by toolness** [comment]
Ooo yeah!  I like "nest", it's what I'm currently using in the codebase.

Do you have a preference of YAML vs. TOML?  If you're ok with the slightly more "codey" look of it (needing to enclose text in quotes, surrounding lists of things with square brackets etc) then that would be my preference, simply because an unexpected downside of YAML is that it is sometimes so "human-friendly" that it ends up getting interpreted in really unexpected ways, which can break the software that relies on it.  But I'm also fine with YAML too.

**Comment by toolness** [comment]
Oh sorry, I just noticed you said above that you didn't mind whether it's TOML or YAML.  Cool, I will set us up with TOML then!

**Comment by toolness** [comment]
Ok @ninapaley I added some very basic support for this in #33!

Actually defining the metadata for a brand-new symbol, or a symbol that doesn't already have metadata associated with it, might be a bit annoying: you'll have to copy the contents of [`svg/_template.toml`](https://github.com/toolness/mystic-symbolic/blob/main/svg/_template.toml) to a new file that is named using the naming system we discussed above (that is, having the same name as the SVG but ending in `.toml` instead of `.svg`).  Once you save that file to the repository, the website's vocabulary builder will slurp it in.

Right now there are only two properties, based on the needs you mentioned in https://github.com/toolness/mystic-symbolic/issues/17#issuecomment-786696966... At present if you try adding new ones that it doesn't recognize, the vocabulary builder will explode (as part of that whole "crash early" philosophy) but we can revisit it if it becomes a burden.  For now just make sure you look at the [Actions tab](https://github.com/toolness/mystic-symbolic/actions) after you make any changes to see if there's a big red "x" next to anything (hopefully it will be a bunch of green checkmarks).  If there is a big red x, keep clicking on the text next to it until you see a white-on-black log of the vocabulary builder's activity, and hopefully you will be able to figure out why it exploded. But if not just ping me and I should be able to fix it!

Oh um the only other thing is that the two properties I added **don't actually do anything yet**!  So um, you can define metadata, but it won't actually affect anything, which is bad.  I will make it actually affect things very soon!

**Comment by ninapaley** [comment]
I will wait until they actually do something, then I will start adding! Do I upload them to the same .svg folder the symbols are in?

**Comment by toolness** [comment]
Ok sounds good, I am working on making them actually do something right now :)

Yup you upload them to the same `svg` folder the symbols are in--my thought was that when you list the files alphabetically, the SVGs would appear right next to their corresponding metadata files, which would hopefully make editing easier.

Err maybe we should rename that folder to `symbols` since it has more than just SVGs in it now, hehe.
