### ISSUE TITLE
New specs color code

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#21]
Arrows:

* ANCHOR POINT = red `#FF0000`
* LEGS = yellow  `#FFFF00`
* WINGS/ARMS = green `#00FF00`
* HORNS = cyan `#00FFFF`
* CROWN = blue `#0000FF`
* TAIL = dark red `#BE0027`
* ~~HALF LINE = lt. yellow `#F7F409`~~

Other:

* BOUNDING BOX = magenta `#FF00FF`
* ~~HALF LINE = lt. yellow `#F7F409`~~

There are currently 3 symbols with these colors in their specs layers. The HALF LINE is included but irrelevant on "fish_head" and "fish_tail" but is significant on "hand_open_3_4". It shows where a connected symbol should line up; the matching light yellow arrow is for orientation.

**Comment by ninapaley** [comment]
Let's forget the HALF LINE. I will just create some symbols specifically designed to be connected this way, and add a "half" specification in its associated metadata file. They can connect tail-to-anchor like everything else. So no light yellow  (F7F409) recognition needed for now. 
Still need dark red (BE0027) to distinguish tail from anchor point.

**Comment by toolness** [comment]
Ok @ninapaley, I just added the new "anchor" attachment point and changed the color for the "tail" attachment point in #23!  Right now this means that no SVGs have tail attachment points, since they're all interpreted as being anchor attachment points now.  But once you add tail attachment points to them, all will be well!

**Comment by ninapaley** [comment]
@toolness I've added tail attachment points to all the symbols, but uploading them failed. I tried uploading just one instead of a batch, and that also failed. Can you please try to pinpoint the problem so I can fix if it's on my end? Thanks.

**Comment by toolness** [comment]
Hey this works now, right? I'm gonna close this issue but feel free to re-open it if you disagree!
