### ISSUE TITLE
Remove Attachments to Anchor Point

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#29]
Now that we have the complexity slider, which I love, I can see that symbols are still attaching to anchor points, even though we now have tail points. Here is a typical example:
![Screen Shot 2021-02-23 at 8 38 10 AM](https://user-images.githubusercontent.com/79212762/108859116-828f7400-75b2-11eb-9f54-0354c5ed0fb3.png)
The "fire" symbol has attached to the "eye" anchor point, so it's mostly obscured and interferes with the silhouette. I would like NOTHING attaching itself to the anchor point, which points inward; the anchor point is where a symbol attaches to something else.

**Comment by toolness** [comment]
Oh doh, sorry about that! I believe I just fixed it.  Give it a few minutes for the changes to make their way to the website, and let me know if you still see that behavior happening...
