### ISSUE TITLE
Attachment point rules

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#49]
Much as I love the random attaching in the Creature maker, we should have the option of applying rules, an attachment rule mode as well as the current random mode. I guess there could be a toggle, "attachment rules," set to ON or OFF (what we have now is OFF, things attach randomly with no rules). 

Each symbol's attachment points are color coded: 
crown = blue
horns = cyan
wings/arms = green
legs = yellow
tail = dark red

I propose modifying symbol TOMLs as follows:
"attach_to = crown, wing" would specify which points this symbol is eligible to attach to, in rules mode. It's like saying, "this symbol is a crown and a wing." Some symbols will only be wings, some will only be tails. Some will be both, and some will be all.

If the above sentence structure doesn't work, then I guess for each symbol the same info could be expressed like this:
crown = true
horn = false
wing = true
leg = false
tail = false

A second category of each symbol would be
"attachment_rules = true"
This line would ALWAYS attach other symbols according to rules, even in random mode. So a symbol with this turned on would always have a head attached to the top, wings attached to the side, and a tail attached to the bottom, even when attachment-rule mode is off.

@toolness what's the best way for me to express these in the TOMLs? Please suggest better ways or, if these look good, I will get typing.

**Comment by toolness** [comment]
Oh cool I like this idea.

For the `attach_to` thingy, I think the easiest thing to do would be to use an array of strings, which in TOML would look like this:

```toml
attach_to = ["tail", "leg", "arm", "horn", "crown"]
```

The above snippet would really be the default if `attach_to` wasn't explicitly specified.  I recommend using the names in the above snippet because they're [what we already use in the source code](https://github.com/toolness/mystic-symbolic/blob/ad3050032309298fb3e3b24e90336be4354a6460/lib/specs.ts#L15-L22).

I'd also like to add a bit of validation to the `attach_to` array... if it finds an item in `attach_to` that isn't one of those strings, should it explode, or should it log a warning?  Do you have a preference?  I think it makes sense to explode if you don't plan on adding more types of attachment points anytime soon, but otherwise it might be easier to keep it more tolerant.

For the `attachment_rules = true` do you mind if we call it `force_attach_to = true`?  That way it's a bit more clear that the property is related to the `attach_to` property, and more indicative of the intent that the rules should always be enforced, rather than being a preference...

**Comment by ninapaley** [comment]
I love those suggestions, thank you!

To be clear, if a TOML doesn't have any attach_to line, it will default to 
attach_to = ["tail", "leg", "arm", "horn", "crown"]

So if I'm specifying a leg, for example, I would write
attach_to = ["leg"]

and that's it, right?

**Comment by toolness** [comment]
Yup, that's right!

**Comment by ninapaley** [comment]
> I'd also like to add a bit of validation to the `attach_to` array... if it finds an item in `attach_to` that isn't one of those strings, should it explode, or should it log a warning? Do you have a preference? 

Let's have it not explode please. I might indeed come up with additional attachment points and if I do, I'd like the flexibility to start adding text specifications.

**Comment by ninapaley** [comment]
What if I want a symbol to not attach to anything in attachment rules mode, but only potentially be a center with things attached to it? I'm thinking of the horse, that won't make a good crown, horn, arm, leg or tail, but could still be nested in things or be a center with things attached to it. How would I specify that?

**Comment by ninapaley** [comment]
Would the way to express this be "attach_to = false"? Then it wouldn't attach to anything in attachment rules mode. Maybe "attachment_rules_mode = false"? Please advise @toolness . I'm modifying the TOML files now.

> What if I want a symbol to not attach to anything in attachment rules mode, but only potentially be a center with things attached to it? I'm thinking of the horse, that won't make a good crown, horn, arm, leg or tail, but could still be nested in things or be a center with things attached to it. How would I specify that?

**Comment by ninapaley** [comment]
In fact, there are so many symbols that shouldn't attach anywhere in attachment rules mode, how about if I just leave out this line entirely, it means they won't attach in attach rules mode, but can still be centers and nested? I.e., no "attach_to" specifications at all defaults to simply not attaching in rules mode. 
Aletrnately, could I express this as, "attach_to = false"? So some would say, "attach_to = ["tail", "leg"]" (attach only to tail or leg points in rules mode)  and others would say "attach_to = false" (don't attach to anything in rules mode) Please advise @toolness .

**Comment by ninapaley** [comment]
OK I have modified a number of TOMLs (I have a backup file of the previous TOMLs, just in case) but will wait to upload them until I get the go-ahead from you, @toolness, since I don't want to make anything explode!

**Comment by toolness** [comment]
Oof, sorry for the late reply--oh what about just `attach_to = []`?  That's just an empty list, which is the same thing as saying "don't attach to _anything_.  We _could_ do your `attach_to = false` thingy but it would require more code on my end, so `attach_to = []` would be preferable if you're amenable to that.

**Comment by toolness** [comment]
Boop!  @ninapaley does the above seem OK?

**Comment by ninapaley** [comment]
That's great, thanks!
(Sorry I didn't see your response until now, Gmail sent the alert to the wrong folder.)

**Comment by toolness** [comment]
Awesome!  Feel free to start adding it to the TOML (it shouldn't explode) and I'll add support for adhering to this new rule soon!

**Comment by toolness** [comment]
Ok I think I just implemented this one @ninapaley! Let me know if it doesn't work as you expect it to.

**Comment by ninapaley** [comment]
Yay! I've added so many symbols I need to go back and modify more TOMLs. Now I'M gonna be somewhat delayed, since I'm fully booked tomorrow. But I should get back on it on Saturday.
