### ISSUE TITLE
Creature page defaults to complexity level 2

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#53]
This should be an easy one. Right now the Creature page defaults to level bonkers. I'd like it to default to level 2, my preferred level.
Ideally it would also default to "Randomly invert symbols" too. Those are the best-looking settings, and visitors ought to get the best-looking experience by default.

**Comment by toolness** [comment]
Ok I think I fixed this one, let me know if anything is amiss @ninapaley !
