### ISSUE TITLE
Reduce max symbols on Mandala to 20

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#69]
Maximum number of symbols on Mandalas ( #24 ) on randomizer should be limited to 20, for now. We can (easily I believe) raise this again if desirable. For now, as we explore the Mandala-izer, a lower maximum should make random mandalas look better.

**Comment by toolness** [comment]
Thanks for filing this @ninapaley!

This is a great candidate for someone's first contribution to the codebase; @webaissance or @mittimithai, would either of you like to take this one on?  If no one responds after a day then I'm happy to do it.

**Comment by toolness** [comment]
Actually @ninapaley, if you're interested in getting your hands dirty with a little bit of code, you could potentially fix this issue yourself too!

**Comment by ninapaley** [comment]
@toolness Oh my! I'll give it a try but someone patient has to teach me.

**Comment by ninapaley** [comment]
I've been trying to figure it out with GitHub's tutorials, but I'm tired today and gave up. Please make the change when you get a chance @toolness .

**Comment by toolness** [comment]
Oh no!!! Sorry @ninapaley I didn't mean for you to try fixing this issue without any assistance from me... I'm happy to show you the ropes!  If you just want to see this issue fixed for now, though, I'm happy to just fix it and leave your first code contribution for a later date. :)

**Comment by ninapaley** [comment]
@toolness Yeah for expediency's sake please just fix it; when you have time for a lesson you can walk me through how to do similar. Thanks!

**Comment by toolness** [comment]
Oh ok, will do!  Just fixed it in 7c05f78, changes should be live soon!

**Comment by ninapaley** [comment]
@toolness Much better now! Thanks.
