### ISSUE TITLE
I broke it

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#8]
Yay I broke the creature maker! I renames the symbols with no caps and replaced spaces with underscores. Then I deleted the old symbols and replaced everything. Now it no worky, I assume because the code references symbols with names that no longer exist. Whee!

**Comment by ninapaley** [comment]
I temporarily fixed it by making a duplicate of "muscle_arm" renamed "muscle arm" and added it to the repository. The code that refers to "muscle arm" should be fixed, but for now the toy works again!

**Comment by toolness** [comment]
Oh nice detective work!  Yup, that's likely what happened, I will change my code to refer to `muscle_arm` later today!

**Comment by toolness** [comment]
Oh cool, it looks like your #9 fixed this on the code side!  I've removed the original `muscle arm.svg` in #11 now that it's no longer needed by the code, so that should close out this issue.  Thanks!
